name: Publish
on:
  push:
    branches: main
jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: angular-calendar-ui
        run: cd projects/angular-calendar-ui

      - name: Install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
