name: Publish
on:
  push:
    branches: main

jobs:
  release:
    name: Publish
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: get list
        run: ls

      - name: Install dependencies
        run: npm ci

      - name: build
        run: npm run build:lib

      - name: setup semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish
        run: npm publish --access public
        working-directory: dist/angular-calendar-ui
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
